### PR TITLE
LxQt to LXQt renaming

### PR DESCRIPTION
**Pull request by paulolieuthier**

### CODE REVIEW

**Comment by luis-pereira** [comment]
@paulolieuthier Can this be done after https://github.com/lxde/liblxqt/pull/51 and gets in ?

**Comment by paulolieuthier** [comment]
@luis-pereira sure.

**Comment by paulolieuthier** [comment]
I'll wait a couple days now that you merged #51.

**Comment by jleclanche** [comment]
@paulolieuthier ping

**Comment by paulolieuthier** [comment]
Rebased.

**Comment by paulolieuthier** [comment]
@jleclanche, @palinek, @agaida, @luis-pereira please, take a look at this.

**Comment by jleclanche** [comment]
Go for it

**Comment by paulolieuthier** [comment]
Done. I tested all the repos for several days.

**Pull request merged**
