### PR TITLE
lxqt_translate_desktop: pass -h instead of --no-filename to grep which is compatible with Busybox

### PR DESCRIPTION
**Pull request by fluxer**
https://www.gnu.org/software/grep/manual/grep.html#Output-Line-Prefix-Control

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm, thanks

**Comment by fluxer** [comment]
@jleclanche 
I'm sorry, can you clarify the meaning of gtm here? (English is not my native language)

**Comment by jleclanche** [comment]
GTM stands for "good to merge", it's intended for the other developers.

**Comment by fluxer** [comment]
ok, thanks.

**Comment by luis-pereira** [comment]
@jleclanche @fluxer The same issue is present in compton-conf, obconf-qt and screengrab  also.

**Comment by jleclanche** [comment]
@luis-pereira ill let you take care of it.

**Comment by luis-pereira** [comment]
@jleclanche Done.
Don't take me wrong, but I wonder what's the meaning of that sentence.

**Comment by jleclanche** [comment]
Not sure what you mean.

**Comment by luis-pereira** [comment]
nevermind.

**Pull request merged**
