### PR TITLE
Adds "automatic" plugin translations loader support

### PR DESCRIPTION
**Pull request by luis-pereira**
Q_COREAPP_STARTUP_FUNCTION can also be used with libs. That's great.

Its part of the solution for https://github.com/lxde/lxqt/issues/766
and the translations loader problems described at
https://github.com/lxde/lxqt-panel/pull/228

### CODE REVIEW

**Comment by palinek** [comment]
Looks nice and simple. Does it correcly work also with static libraries (lxqt-panel plugins?

**Comment by luis-pereira** [comment]
@palinek `Q_COREAPP_STARTUP_FUNCTION` works with static libs as well.
I was experiencing some weird (at least to me) issue. If put on it's own file the `Q_COREAPP_STARTUP_FUNCTION` doesn't get called. If put or included in an existing file it works ok. Something related to symbol visibility I think. 
Resuming my "investigation".

**Comment by palinek** [comment]
> I was experiencing some weird (at least to me) issue. If put on it's own file the Q_COREAPP_STARTUP_FUNCTION doesn't get called. If put or included in an existing file it works ok. Something related to symbol visibility I think. 

Isn't the Q_COREAPP_STARTUP_FUNCTION somehow preprocessed by `moc` -> expecting it in header? (just a blind shot)

**Comment by luis-pereira** [comment]
I also think on that. But it works Ok with shared libs, that discards it.
Also `Q_COREAPP_STARTUP_FUNCTION` is an macro. See [here](https://github.com/qtproject/qtbase/blob/dev/src/corelib/kernel/qcoreapplication.h#L256).

I will push my findings/ Maybe you can help debugging it,

**Comment by luis-pereira** [comment]
@palinek Testing with debug info:
* Checkout https://github.com/lxde/liblxqt/tree/dbg-plugin-translation-loader
* General solution (not working for static libs): https://github.com/lxde/lxqt-panel/tree/plugin-translation-loader
* Specific static solution: https://github.com/lxde/lxqt-panel/tree/dbg-plugin-translation-loader

I'm missing something here

**Comment by palinek** [comment]
@luis-pereira I can't bite through it either....

Seems like it has something to do with the weak/strong symbol & static library linking ... something similar to [this](http://stackoverflow.com/questions/30355013/linking-with-static-library-not-equivalent-to-linking-with-its-objects)
- when i've modified the linking command to ... -Wl,--whole-archive ../plugin-mainmenu/libmainmenu.a -Wl,--no-whole-archive... function is executed
- I don't see any difference in defined symbols when the translation logic is in generated file and in "sources" file; here both used (generated & in source):
```
$ nm plugin-mainmenu/libmainmenu.a | c++filt | egrep -i translatio
00000000000001c1 r .L__PRETTY_FUNCTION__._ZL21loadPluginTranslationv
0000000000002850 t loadPluginTranslation()
0000000000002830 t loadPluginTranslation_ctor_function()
0000000000000000 t (anonymous namespace)::loadPluginTranslation_ctor_function_ctor_class_::loadPluginTranslation_ctor_function_ctor_class_()
0000000000000000 b (anonymous namespace)::loadPluginTranslation_ctor_function_ctor_instance_
00000000000029c0 t loadPluginTranslation()::$_0::operator()() const
0000000000002a30 t loadPluginTranslation()::$_1::operator()() const
00000000000001b8 r loadPluginTranslation()::$_0::operator()() const::qstring_literal
0000000000000180 r loadPluginTranslation()::$_1::operator()() const::qstring_literal
LXQtPluginTranslationLoader.cpp.o:
0000000000000020 t _GLOBAL__sub_I_LXQtPluginTranslationLoader.cpp
000000000000005b r .L__PRETTY_FUNCTION__._ZL21loadPluginTranslationv
0000000000000040 t loadPluginTranslation()
0000000000000020 t loadPluginTranslation_ctor_function()
0000000000000000 t (anonymous namespace)::loadPluginTranslation_ctor_function_ctor_class_::loadPluginTranslation_ctor_function_ctor_class_()
0000000000000000 b (anonymous namespace)::loadPluginTranslation_ctor_function_ctor_instance_
0000000000000160 t loadPluginTranslation()::$_0::operator()() const
00000000000001d0 t loadPluginTranslation()::$_1::operator()() const
0000000000000030 r loadPluginTranslation()::$_0::operator()() const::qstring_literal
0000000000000000 r loadPluginTranslation()::$_1::operator()() const::qstring_literal
```
- it si probably not a good idea to have same symbols in multiple palces (libraries)

If there is something wrong with the symbols and linker... it always seems like a woodo to me :(

**Comment by palinek** [comment]
...tried also additg the `-W,l-force_load`, `W,l-all_load` as suggestede [here](http://stackoverflow.com/questions/16294842/how-to-disable-c-dead-code-stripping-in-xcode)...but still no luck

**Comment by palinek** [comment]
...and base on this [guy](http://stackoverflow.com/questions/9459980/c-global-variable-not-initialized-when-linked-through-static-libraries-but-ok)... we probably have to make a workaround for static libraries => reference some symbol from the `LXQtPluginTranslationLoader.cpp` to force the linker not strip it.

**Comment by palinek** [comment]
@luis-pereira 
just pushed:
- https://github.com/lxde/liblxqt/commit/0c29cfc4c570bc3d3099d995849cdd5f42910d39
- https://github.com/lxde/lxqt-panel/commit/1d9d9df41e2ba1bcc59268a37ac7871fe9ef5ad8

...with those the translation is perfomed for static and dynamic plugins (and the plugin on its own doesn't know if it is static/dynamic).

Note: the panel is crashing all the time at the end (ctrl+c) with this new translation loading (also without my changes):
```
(gdb) bt
#0  0x00007f8e78fb5ca4 in QGenericAtomicOps<QBasicAtomicOps<4> >::load<int> (_q_value=@0x7f8e5aeede58: <error reading variable>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h:90
#1  QBasicAtomicInteger<int>::load (this=0x7f8e5aeede58) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h:110
#2  0x00007f8e78fb5c09 in QtPrivate::RefCount::deref (this=0x7f8e5aeede58) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h:60
#3  0x00007f8e78fb5bcf in QString::~QString (this=0x1d966a0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:992
#4  0x00007f8e78fb886c in QHashNode<QString, QHashDummyValue>::~QHashNode (this=0x1d96690) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:197
#5  0x00007f8e78fb87ed in QHash<QString, QHashDummyValue>::deleteNode2 (node=0x1d96690) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:545
#6  0x00007f8e7545fbd9 in QHashData::free_helper (this=0x1d8b3c0, node_delete=0x7f8e78fb87d0 <QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*)>)
    at tools/qhash.cpp:493
#7  0x00007f8e78fb8823 in QHash<QString, QHashDummyValue>::freeData (this=0x7f8e791edd90 <LXQt::Translator::translatePlugin(QString const&, QString const&)::loadedPlugins>,
    x=0x1d8b3c0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:581
#8  0x00007f8e78fb8ebc in QHash<QString, QHashDummyValue>::~QHash (this=0x7f8e791edd90 <LXQt::Translator::translatePlugin(QString const&, QString const&)::loadedPlugins>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:302
#9  0x00007f8e78fb7a65 in QSet<QString>::~QSet (this=0x7f8e791edd90 <LXQt::Translator::translatePlugin(QString const&, QString const&)::loadedPlugins>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:63
#10 0x00007f8e74756bc9 in __run_exit_handlers (status=0, listp=0x7f8e74ac25a8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#11 0x00007f8e74756c15 in __GI_exit (status=<optimized out>) at exit.c:104
#12 0x00007f8e74740b4c in __libc_start_main (main=0x47f980 <main(int, char**)>, argc=3, argv=0x7fff05978268, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff05978258) at libc-start.c:321
#13 0x000000000047f8a4 in _start ()
(gdb)
```

**Comment by palinek** [comment]
The crash is another woodoo with static variables and their destruction order (undefined). If we remove the static hash for checking if the translator was loaded:
```diff
diff --git a/lxqttranslator.cpp b/lxqttranslator.cpp
index 841f84e..fef42e1 100644
--- a/lxqttranslator.cpp
+++ b/lxqttranslator.cpp
@@ -168,6 +168,8 @@ bool Translator::translateLibrary(const QString &libraryName)
 
 bool Translator::translatePlugin(const QString &pluginName, const QString& type)
 {
+    /* XXX: no need to check as we are loading translation in plugin static initialization time (& with use of Q_COREAPP_STARTUP_FUNCTION)
+     * and the QPluginLoader ensures that the library will be loaded only once. Static plugins also ensure to call this only once.
     static QSet<QString> loadedPlugins;
 
     QString fullName = type % QChar('/') % pluginName;
@@ -175,6 +177,7 @@ bool Translator::translatePlugin(const QString &pluginName, const QString& type)
         return true;
 
     loadedPlugins.insert(pluginName);
+    */
     return translate(pluginName, type);
 }
```
... everything works fine

**Comment by palinek** [comment]
@luis-pereira The static finalization SEGFAULT is somehow caused by the `QStringLiteral` and the resulting static 'QString` being disposed sooner than the static `QHash` in lxqttranslator.cpp....

**Comment by luis-pereira** [comment]
@palinek That makes sense. Merge it, pls.

**Pull request merged**
