### PR TITLE
LXQtTheme: Remove (outdated) "singleclick" qss assembly

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/lxqt#940

Do I miss something or is the reasoning (i've written into the commit log message) 100% valid?

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Good catch. 100% valid AFAIK. GTM.

**Comment by palinek** [comment]
> Good catch. 

...I wasn't good enough to get it straight and had to dig deeply into the QT core :disappointed:

**Comment by paulolieuthier** [comment]
Good to have you on board. :smile:

**Comment by pmattern** [comment]
@palinek 
83c93de seems to fix the problem depicted in lxde/lxqt#940.
Interestingly, lxqt-panel did not have to be recompiled against 83c93de but the problem ceased once the new liblxqt version was installed (and did not come up again after recompiling the panel against 83c93de).

**Comment by palinek** [comment]
> Interestingly, lxqt-panel did not have to be recompiled against 83c93de

It's not a surprise, the change does not break API nor ABI compatibility... so no need to recompile any other component using it.

**Comment by palinek** [comment]
...merging

**Pull request merged**
