### PR TITLE
Use the new LXQt Build Tools package

### PR DESCRIPTION
**Pull request by luis-pereira**
Remove all the stuff moved to the lxqt-build-tools repository.

### CODE REVIEW

**Comment by palinek** [comment]
How about pulling the lxqt-build-tools also in `lxqt-config.cmake`, then we don't need to do any changes into projects which have liblxqt run-time dependency.
In particular I mean:
```diff
diff --git a/cmake/lxqt-config.cmake.in b/cmake/lxqt-config.cmake.in
index 3d6f0c8..9c1a6e5 100644
--- a/cmake/lxqt-config.cmake.in
+++ b/cmake/lxqt-config.cmake.in
@@ -57,6 +57,7 @@ find_dependency(Qt5X11Extras @QT_MINIMUM_VERSION@)
 find_dependency(Qt5LinguistTools @QT_MINIMUM_VERSION@)
 find_dependency(Qt5Xdg @QTXDG_MINIMUM_VERSION@)
 find_dependency(KF5WindowSystem)
+find_dependency(lxqt-build-tools @LXQTBT_MINIMUM_VERSION@)
 
 if (CMAKE_VERSION VERSION_GREATER 2.8.12)
     cmake_policy(SET CMP0024 OLD)
```

(tried just with the lxqt-admin, but all others should work also)

**Comment by luis-pereira** [comment]
@palinek I'm aware of that. That's a way to go. I will bring that (and other stuff) up to discussion.

**Comment by agaida** [comment]
hmm - thb i would prefer _all_ dependencies in the relevant CMakeLists - might be more work, but i would really avoid the cmake magic here - it might be that i'm more than a litte bit old fashioned - but i would really prefer to see all dependencies if i open the root CMakeLists. Nothing against the more sophisticated solution, this is my pov as distribution packager.

**Comment by palinek** [comment]
> hmm - tbh i would prefer all dependencies in the relevant CMakeLists ...but i would really prefer to see all dependencies if i open the root CMakeLists

I don't agree here. It's the very same as with the package dependencies. Example:
- _our_ package depends on _dep1_, _dep2_
- _dep1_ depends on _dep1.1_, _dep1.2_
- _dep2_ depends on _dep2.1_, ..., _dep2.n_

=> will you make _our_ depend on _dep1_, _dep2_, all _dep1.X_ and all _dep2.X_ ?

**Comment by agaida** [comment]
@palinek - hmm - i think about again, you are right, we should do the integration your way

**Pull request merged**
