### PR TITLE
Update Greek (el) translation

### PR DESCRIPTION
**Pull request by dglent**
Update Greek translation

### CODE REVIEW

**Comment by jleclanche** [comment]
What did you use to generate this? The output looks wrong.

**Comment by dglent** [comment]
I didn't generate it. I 've just update the translations of the current file <liblxqt_el_GR.ts> 
I used Lokalize and the i opened it also in qt5linguist to check if there are any errors and it was ok.

**Comment by jleclanche** [comment]
When you update it in a tool, the xml gets regenerated. This particular tool unescaped `&gt;`, changed quoting and attribute ordering...

Weird, anyway, gtm

**Comment by pmattern** [comment]
What about attribute "vanished"?
To my knowledge it is used to tag elements that are no longer needed due to changes in the actual source code. The idea is to avoid translation work that has already been done getting lost by just tagging instead of deleting from the TS files. So no point in translating those items, AFAIK.

**Comment by dglent** [comment]
I think that Lokalize has removed the tags (i don't know why) but normally it is not a problem. 
I didn't have any problem with translations and i translate all ts files with Lokalize in order to use the spell check, the TM and the Glossary which i have collated since many years.
They should be tagged again in next lupdate run.

**Comment by dglent** [comment]
I updated the commit and i removed the country specific.
Saving with qt5linguist it has fixed some changes in xml syntax as the place of the 'line=' at the end of the line of the 'location' tag

**Pull request merged**
