### PR TITLE
Move lxqt version

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by palinek** [comment]
But this is definitely not sufficient...with these changes, you only "override" the version for the `liblxqt`, but not for including into other components. Other components will still see/use the version parameters from `lxqt-buildtools` -> https://github.com/lxde/liblxqt/blob/master/cmake/lxqt-config.cmake.in#L18.

**Comment by agaida** [comment]
damn, i know there was something else :) - will fix it today

**Comment by agaida** [comment]
@luis-pereira @palinek any objections?

**Comment by palinek** [comment]
GTM

**Comment by luis-pereira** [comment]
GTM.

**Pull request merged**
