### PR TITLE
LxQt::Application: unix signal handling & quit

### PR DESCRIPTION
**Pull request by palinek**
references lxde/lxqt#714

### CODE REVIEW

**Comment by luis-pereira** [comment]
@palinek @palinek Thinking out loud here:  How do we allow the user to run it's code ?

Sorry for the delays. My time has been taken by the Targets stuff and my laptop that just surrender it's soul to the creator :cry:

**Comment by palinek** [comment]
> Thinking out loud here: How do we allow the user to run it's code ?

Do we want also some universal mechanism to allow children of `LXQt::Application` class install/execute it's own logic for handling (any) signals?

**Comment by luis-pereira** [comment]
@palinek IMO yes. It's the app developer that knows what should be done. What's your opinion ?

**Comment by palinek** [comment]
@luis-pereira something like in @a1fe5a4 ?

**Comment by luis-pereira** [comment]
@palinek Yes. Something like that :smile: Only took a quick look

**Comment by palinek** [comment]
...squashed... is it mergable now?

**Comment by luis-pereira** [comment]
@palinek IMO Yes.

**Pull request merged**
