### PR TITLE
add executable to handle leave actions

### PR DESCRIPTION
**Pull request by dbluelle**
new attempt for https://github.com/lxde/lxqt/issues/319

### CODE REVIEW

**Comment by antis81** [comment]
If you ask me, yes :smile:. But I'm just a user.

**Comment by jleclanche** [comment]
Due to lack of feedback from others, I'm pushing for this. There's been a lot of back and forth on this and we need some form of it in 0.9 anyway.

Landed in 63cf48a.

**Comment by PCMan** [comment]
Maybe lxqt-session is a better place to put this command?
It's reasonable for a session manager to provide a tool for quitting the
session.
We used to do this in lxde.
2015/1/12 下午3:33 於 "Jerome Leclanche" <notifications@github.com> 寫道：

**Comment by jleclanche** [comment]
I want this in lxqt-session, but someone (I think it was you, actually) argued against it because they didn't want users to be locked into lxqt-session.

**Comment by PCMan** [comment]
2015/1/12 下午3:55 於 "Jerome Leclanche" <notifications@github.com> 寫道：
>
> I want this in lxqt-session, but someone (I think it was you, actually)
argued against it because they didn't want users to be locked into
lxqt-session.
It was me? Ouch!
Well, this can be useful as a standalone program.
However, if nobody wants to maintain a separate package, we need some
tradeoff.
Then lxqt-session is probably the best place for the tool.

**Comment by jleclanche** [comment]
I'm +1 on moving it to lxqt-session. Let's wait on other people's feedback but this needs to happen before the end of the week if it happens. ping @surlykke @paulolieuthier @luis-pereira

**Comment by Vladimir-csp** [comment]
I vote for modularity, but i`m just a user here.

**Comment by jleclanche** [comment]
This wouldn't be a problem if we could eg. rely on systemd being present, seeing as systemd has APIs which handle this so we could just rely on this. My suggestion if you do use a different session manager and for whatever reason you *need* those shortcuts, you should use a systemd call in the desktop file. If you don't have systemd, there are other wrappers you can install...

**Comment by paulolieuthier** [comment]
I'm actually happy with both solutions. @PCMan's arguments before and now are strong.

**Comment by agaida** [comment]
i think that the session is the best place for it - i don't like micro packages.

**Comment by jleclanche** [comment]
@PCMan we have enough agreement to justify the move imo. Can you take care of it? Or @agaida?

**Comment by PCMan** [comment]
Assign to me if no other people can do it.
I don't have time for coding now but can handle it next week.
2015/1/12 下午7:17 於 "Jerome Leclanche" <notifications@github.com> 寫道：

**Comment by jleclanche** [comment]
@agaida said on IRC he can pick it up.

**Comment by agaida** [comment]
fine, will do that

**Comment by dbluelle** [comment]
I think the main reason for _not_ putting this into lxqt-session was that if we do that,
lxqt-panel may need a hard dependency on lxqt-session.
(see https://github.com/lxde/lxqt-panel/pull/93 and https://github.com/lxde/lxqt/issues/319 )
lxqt-panel will not have any "leave" buttons without the desktop files,
or am I missing something here?

**Comment by agaida** [comment]
@dbluell - no, not really - if the session isn't installed, there is no desktop-file nor executable - so what? Maybe i miss something too :)

**Comment by jleclanche** [comment]
It's a soft dependency, not a hard dependency.

**Comment by dbluelle** [comment]
>  The only thing is - you cant place these things into a quick-starter, the start menu functionality should not be touched.

Does that mean we should drop https://github.com/lxde/lxqt-panel/pull/93 ?
Without that PR it will still not be possible to drag/drop the leave actions into a quick-starter 
(which is the whole point why I started this... )

**Pull request closed without merging**
