### PR TITLE
lxqtpower: prefer systemd as a power provider

### PR DESCRIPTION
**Pull request by paulolieuthier**

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@luis-pereira @PCMan @jleclanche @surlykke @palinek please give an opinion here.

**Comment by palinek** [comment]
I would say GTM, but my opinion here is irrlevant because about powermanagement I know literaly nothing.

**Comment by surlykke** [comment]
2015-04-20 3:57 GMT+02:00 Paulo Lieuthier <notifications@github.com>:

> @luis-pereira <https://github.com/luis-pereira> @PCMan
> <https://github.com/PCMan> @jleclanche <https://github.com/jleclanche>
> @surlykke <https://github.com/surlykke> @palinek
> <https://github.com/palinek> please give an opinion here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/liblxqt/pull/40#issuecomment-94335787>.
>
lgtm.


br. Chr.

**Comment by jleclanche** [comment]
GTM

J. Leclanche

**Comment by paulolieuthier** [comment]
Merged in lxde/liblxqt@fe74e89c624f28149e7c6678b98c031bf5257af0.

**Pull request closed without merging**
