### PR TITLE
consolekit2 Suspend/Hibernate

### PR DESCRIPTION
**Pull request by jordi-pujol**
support consolekit2 power management, functions Suspend and Hibernate

### CODE REVIEW

**Comment by jleclanche** [comment]
1. Please give the commit a more descriptive title
2. You're adding returns before break statements, please remove the `break`s.

**Comment by jleclanche** [comment]
code looks ok but untested so ping anyone who can test this.

**Comment by jordi-pujol** [comment]
all my code is tested by myself,

how can we find a volunteer if we need more testers ?

**Comment by jleclanche** [comment]
Need to test if it breaks existing functionality, more than whether the new stuff works.

**Comment by luis-pereira** [comment]
Can't help right now. I'm working on upgrading the build system and don't have all of the lxqt installed

**Comment by jordi-pujol** [comment]
I have created a filesystem image for LXQT + systemd
it runs correctly, all the power management functionality works

# systemd-cgls > systemd.txt
# dpkg -l liblxqt0 >> systemd.txt

Tested and working,

On Fri, Jun 5, 2015 at 6:57 PM, Jerome Leclanche <notifications@github.com>
wrote:

> Need to test if it breaks existing functionality, more than whether the
> new stuff works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/liblxqt/pull/47#issuecomment-109362122>.
>

├─1 /sbin/init root-clean
├─service.slice
│ ├─service-spool.slice
│ │ └─cups.service
│ │   └─3540 /usr/sbin/cupsd -f
│ └─service-server.slice
│   ├─lnet-set-cgroups.service
│   │ ├─2856 /bin/sh /usr/sbin/lnet-set-cgroups start
│   │ ├─2881 inotifywait --quiet --monitor --recursive --event create /sys/fs...
│   │ └─2882 /bin/sh /usr/sbin/lnet-set-cgroups start
│   └─systemd-timesyncd.service
│     └─2717 /lib/systemd/systemd-timesyncd
├─system.slice
│ ├─system-ctl.slice
│ │ ├─getty@tty1.service
│ │ │ └─9064 /sbin/agetty --noclear tty1 linux
│ │ ├─systemd-journald.service
│ │ │ └─2303 /lib/systemd/systemd-journald
│ │ ├─udisks2.service
│ │ │ └─9844 /usr/lib/udisks2/udisksd --no-debug
│ │ ├─upower.service
│ │ │ └─9909 /usr/lib/upower/upowerd
│ │ ├─jobadmind.service
│ │ │ ├─3300 /bin/bash /usr/sbin/jobadmind --daemon
│ │ │ ├─3477 /bin/bash /usr/sbin/jobadmind --daemon
│ │ │ ├─5353 /bin/bash /usr/sbin/jobadmind --daemon
│ │ │ ├─5354 /bin/bash /usr/sbin/jobadmind --daemon
│ │ │ ├─5355 /bin/bash /usr/sbin/jobadmind --daemon
│ │ │ ├─5356 inotifywait -e modify /var/tmp/jobadmin.d/splfs_wtr.lst
│ │ │ └─7004 inotifywait -e modify /var/tmp/jobadmin.d/active_jobs.lst /var/t...
│ │ ├─systemd-logind.service
│ │ │ └─3561 /lib/systemd/systemd-logind
│ │ └─polkitd.service
│ │   └─3713 /usr/lib/policykit-1/polkitd --no-debug
│ ├─system-cmn.slice
│ │ └─NetworkManager.service
│ │   ├─ 3538 /usr/sbin/NetworkManager --no-daemon
│ │   └─10132 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper...
│ └─system-sys.slice
│   ├─dbus.service
│   │ └─3301 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopi...
│   ├─ModemManager.service
│   │ └─3581 /usr/sbin/ModemManager
│   ├─accounts-daemon.service
│   │ └─3537 /usr/lib/accountsservice/accounts-daemon
│   ├─colord.service
│   │ └─5310 /usr/lib/colord/colord
│   ├─systemd-udevd.service
│   │ └─2399 /lib/systemd/systemd-udevd
│   └─acpid.service
│     └─3533 /usr/sbin/acpid
├─interactive.slice
│ └─interactive-X.slice
│   └─lightdm.service
│     ├─9069 /usr/sbin/lightdm
│     └─9073 /usr/bin/X -br -dpi 112 :0 -seat seat0 -auth /var/run/lightdm/ro...
└─user.slice
  └─user-1001.slice
    ├─session-1.scope
    │ ├─ 9104 lightdm --session-child 13 16
    │ ├─ 9111 lxqt-session
    │ ├─ 9136 /usr/bin/ssh-agent /usr/bin/dbus-launch --exit-with-session x-s...
    │ ├─ 9139 /usr/bin/dbus-launch --exit-with-session x-session-manager
    │ ├─ 9140 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --s...
    │ ├─ 9156 openbox
    │ ├─ 9159 /bin/sh /usr/bin/lnet-wallpaper.sh
    │ ├─ 9171 pcmanfm-qt --desktop --profile=lxqt
    │ ├─ 9172 lxqt-globalkeysd
    │ ├─ 9173 lxqt-notificationd
    │ ├─ 9174 lxqt-panel
    │ ├─ 9175 lxqt-policykit-agent
    │ ├─ 9176 lxqt-runner
    │ ├─ 9178 /usr/bin/nm-applet
    │ ├─ 9809 /usr/lib/at-spi2-core/at-spi-bus-launcher
    │ ├─ 9810 compton --dbus -b
    │ ├─ 9813 /usr/bin/pulseaudio --start --log-target=syslog
    │ ├─ 9816 /usr/bin/dbus-daemon --config-file=/etc/at-spi2/accessibility.c...
    │ ├─ 9822 /usr/lib/gvfs/gvfsd
    │ ├─ 9828 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
    │ ├─ 9835 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
    │ ├─ 9838 /usr/lib/pulseaudio/pulse/gconf-helper
    │ ├─ 9840 /usr/lib/x86_64-linux-gnu/gconf/gconfd-2
    │ ├─ 9849 /usr/lib/menu-cache/menu-cached /tmp/.menu-cached-:0-jpujol
    │ ├─ 9864 /usr/lib/gvfs/gvfs-mtp-volume-monitor
    │ ├─ 9869 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
    │ ├─ 9873 /usr/lib/gvfs/gvfs-goa-volume-monitor
    │ ├─ 9877 /usr/lib/gvfs/gvfs-afc-volume-monitor
    │ ├─ 9897 /usr/lib/gvfs/gvfsd-trash --spawner :1.8 /org/gtk/gvfs/exec_spa...
    │ ├─ 9933 lxqt-powermanagement
    │ ├─ 9948 sleep 10m
    │ ├─11524 /usr/bin/gksu /usr/bin/x-terminal-emulator
    │ ├─11525 /usr/bin/sudo -H -S -p GNOME_SUDO_PASS -u root -- /usr/bin/x-te...
    │ ├─11527 /usr/bin/x-terminal-emulator
    │ ├─11532 /usr/bin/dbus-launch --autolaunch 14918b0357a74315a8fa830b159be...
    │ ├─11533 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --s...
    │ ├─11535 /bin/bash
    │ └─11544 systemd-cgls
    └─user@1001.service
      ├─9108 /lib/systemd/systemd --user
      └─9109 (sd-pam)
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-====================================================
ii  liblxqt0:amd64 0.9.0-13.ck2 amd64        Shared libraries for LXQt desktop environment (libs)

**Comment by jleclanche** [comment]
gtm but waiting on a 2nd one. And please fix the return/break issues I highlighted.

**Comment by jordi-pujol** [comment]
sorry, of two consecutive messages have seen only the last one.

made some changes in the code,
but as i am a begginer in github, don't know what field is that title ?

**Comment by paulolieuthier** [comment]
This looks very messy. @jordi-pujol what are you trying to do here?

**Comment by jleclanche** [comment]
Closing for lack of updates.

**Pull request closed without merging**
