### PR TITLE
Add XDG_CONFIG_DIRS support

### PR DESCRIPTION
**Pull request by palinek**
ref lxde/lxqt#349, lxde/lxqt#385, lxde/lxqt#250

I don't know if this is enough to close the issues (each component needs to be checked if it doesn't use "plain" QSettings for its configuration).

### CODE REVIEW

**Comment by gilir** [comment]
Great, thanks for time on this issue :-)

If I understand right, you implement it with a build flag, I'm not sure it's practical for a downstream point of view. Example : if you want to build a custom distro Debian-based, you have to rebuild the liblxqt package just to set some custom settings. Usually, you don't have to modify the way packages are build just to change some settings.

On Lubuntu, we heavily use the XDG_CONFIG_DIRS with LXDE. We just have to add /etc/xdg/Lubuntu in the beginning of XDG_CONFIG_DIRS, putting all the modified files here, and it's done. XDG_CONFIG_DIRS is read at runtime, from the beginning of the list of directories in XDG_CONFIG_DIRS. It's also possible for any people to build a custom distro just by adding /etc/xdg/another_diretory to XDG_CONFIG_DIRS, and put their settings into this.

**Comment by palinek** [comment]
> If I understand right, you implement it with a build flag, I'm not sure it's practical for a downstream point of view. Example : if you want to build a custom distro Debian-based, you have to rebuild the liblxqt package just to set some custom settings.

It's default on -> https://github.com/lxde/liblxqt/pull/104/commits/b220d13538b52afdbce7da00fefa4a5796d1fe53#diff-af3b638bc2a3e6c650974192a53c7291R127

I've added the option to easily turn it of in case someone needs that.

**Comment by gilir** [comment]
Sorry, I didn't read the code correctly the first time I though the build flag set only 1 custom dir ... Just reading it again, and I think it does what I had in mind. Thanks :-)
I'll test it later this week to confirm this.

**Comment by palinek** [comment]
I've made the proper implementation directly into qt -> https://github.com/qt/qtbase/compare/dev...palinek:xdg_fallback

Can someone review & test for correctness before submitting it to Qt?

**Comment by palinek** [comment]
Just a note... this will not be needed if the patch(https://codereview.qt-project.org/#/c/169245/) will be accepted in Qt.

**Comment by paulolieuthier** [comment]
From the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html): 

> "The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent."

It makes me think we shouldn't just search for the first available settings file in the directory found. Every setting information should be searched until found. For example:

```bash
$ echo $XDG_CONFIG_DIRS
/etc/xdg/Lubuntu:/etc/xdg
$ cat /etc/xdg/Lubuntu/lxqt/lxqt.conf
[General]
icon_theme=oxygen
$ cat /etc/xdg/lxqt/lxqt.conf
[General]
icon_theme=elementary
theme=light
```

So `icon_theme` should be "oxygen", because of precedence of `/etc/xdg/Lubuntu`, but `theme` should be "light" even though it's not defined in `/etc/xdg`.

**Comment by palinek** [comment]
> It makes me think we shouldn't just search for the first available settings file in the directory found. Every setting information should be searched until found.

Why are you thinking, we are searching only the first one? The logic wants to be "if user specific config file is empty -> search for all system-wide configs and put all their keys/values into the user specific one (so if multiple configs found, the values will be overwritten)".
Note: that this is a workaround, not a proper solution.

**Comment by palinek** [comment]
Hm... but now I've realized that we should iterate the directories in XDG_CONFIG_DIRS in reverted order to achieve correct prioritization.

**Comment by paulolieuthier** [comment]
> Why are you thinking, we are searching only the first one?

Because we're [stopping in the first fle found](https://github.com/lxde/liblxqt/pull/104/files#diff-ca66c268a6ce420d8e5e20768edccca5R77), aren't we?

**Comment by palinek** [comment]
You're right ... pushed the fixup (also for the priority).

**Comment by paulolieuthier** [comment]
Great. The only thing I can think of now is that maybe we should monitor all those files for modifications, and read them all again (maybe this time in order, only looking for diffs).

**Comment by paulolieuthier** [comment]
Fair enough. GTM.

**Pull request closed without merging**
