### PR TITLE
Update lxqtpower.h

### PR DESCRIPTION
**Pull request by delcibao**
fix typo line 106:  LXQt::ScreenSaver mScreenSaver;

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Thanks.

**Comment by delcibao** [comment]
yw. yay! my first pull request

**Comment by paulolieuthier** [comment]
Pretty good! Tip: next time create a new branch for the pull request, so you can still use your master.

**Comment by paulolieuthier** [comment]
And make sure to reach us in #lxde on Freenode.

**Pull request merged**
