### PR TITLE
config dialog: Protect against null pages add.

### PR DESCRIPTION
**Pull request by luis-pereira**
Make it resilient to null pointers pages.

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by jleclanche** [comment]
gtm

**Comment by luis-pereira** [comment]
@palinek The `Q_ASSERT` is removed on release builds as @jleclanche pointed out. It's there to make it stop and print a warning message containing the source code file name and line number, so a developer can debug the issue.

**Comment by palinek** [comment]
I wasn't saying that it will harm in production... I was just trying to say that the check is performed twice in if one calls the QString overload...

**Comment by luis-pereira** [comment]
@palinek I wasn't undertanding what you were saying. This morning I saw what you meant.
Updated PR.

**Comment by palinek** [comment]
GTM :smile:

**Pull request merged**
